apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-demo-deployment
spec:
  selector:
    matchLabels:
      app: k8s
  replicas: 3
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  # Pod 模板
  # 包含 2 部分:
  # - Pod.metadata ，包含了 labels，即跟 selector.matchLabels 相匹配的一个 Labels
  # - Pod.spec，其实是 Deployment 最终创建出来 Pod 的时候，它所用的 Pod.spec
  template:
    metadata:
      labels:
        app: k8s
    spec:
      containers:
      - name: k8s-demo
        image: riskers/k8s-demo:0.2
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "1000m"
        ports:
        - containerPort: 80
