apiVersion: v1
kind: Pod
metadata:
  name: kuard-health
  labels:
    name: kuard-health
spec:
  containers:
  - name: kuard-health
    image: gcr.io/kuar-demo/kuard-amd64:1
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    livenessProbe:
      httpGet:
        path: /health
        port: 8080
      initialDelaySeconds: 5
      timeoutSeconds: 1
      failureThreshold: 3
      periodSeconds: 10
    ports:
      - containerPort: 8080
