apiVersion: v1
kind: Pod
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  containers:
  - name: kuard
    image: gcr.io/kuar-demo/kuard-amd64:1
    volumeMounts:
      - mountPath: /tmp/vol # kuard-data 卷挂载到 /tmp/vol 路径
        name: kuard-data
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  volumes:
    - name: kuard-data # 定义一个名为 kuard-data 的卷
      hostPath:
        path: /tmp/vol